name: Schedule invoices
on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  call-pokemon-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Pokemon API
        run: curl {{ secrets.ENDPOINT}}
