name: Schedule 
on:
  schedule:
    - cron: '45 9 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name:  cron job slack notification
        run: |
          curl --request GET \
          --url 'https://stg.reservations.ioet.com/api/slackBot/users' 