name: Cron Job For Save Invoices

on:
  schedule:
    - cron: "0/6 * * * *" # Every 15 minutes

jobs:
  post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST Request for Save Invoices
        run: |
          curl -X POST \
          'https://stg.api.payroll.ioet.com/invoice/save' \
          --header 'cron-key: AIzaSyDh9JtXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
