name: Cron Job For Save Invoices

on:
  schedule:
    - cron: "0/5 * * * *" # Every 15 minutes

jobs:
  post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST Request for Save Invoices
        run: |
          curl --request POST \
          --url 'https://jsonplaceholder.typicode.com/todos/1' 